package com.nuvio.app.features.player

import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

@Composable
fun PlayerScreen(
    profileId: Int,
    title: String,
    sourceUrl: String,
    sourceAudioUrl: String? = null,
    sourceHeaders: Map<String, String> = emptyMap(),
    sourceResponseHeaders: Map<String, String> = emptyMap(),
    externalSubtitles: List<com.nuvio.app.features.streams.StreamSubtitle> = emptyList(),
    streamType: String? = null,
    providerName: String,
    streamTitle: String,
    streamSubtitle: String?,
    initialBingeGroup: String? = null,
    pauseDescription: String? = null,
    onBack: () -> Unit,
    onOpenInExternalPlayer: ((ExternalPlayerPlaybackRequest) -> Unit)? = null,
    onOpenExternalUrl: ((String) -> Unit)? = null,
    modifier: Modifier = Modifier,
    logo: String? = null,
    poster: String? = null,
    background: String? = null,
    seasonNumber: Int? = null,
    episodeNumber: Int? = null,
    episodeTitle: String? = null,
    episodeThumbnail: String? = null,
    contentType: String? = null,
    videoId: String? = null,
    parentMetaId: String,
    parentMetaType: String,
    providerAddonId: String? = null,
    torrentInfoHash: String? = null,
    torrentFileIdx: Int? = null,
    torrentFilename: String? = null,
    torrentTrackers: List<String> = emptyList(),
    initialPositionMs: Long = 0L,
    initialProgressFraction: Float? = null,
    contentLanguage: String? = null,
) {
    PlayerScreenContent(
        PlayerScreenArgs(
            profileId = profileId,
            title = title,
            sourceUrl = sourceUrl,
            sourceAudioUrl = sourceAudioUrl,
            sourceHeaders = sourceHeaders,
            sourceResponseHeaders = sourceResponseHeaders,
            externalSubtitles = externalSubtitles,
            streamType = streamType,
            providerName = providerName,
            streamTitle = streamTitle,
            streamSubtitle = streamSubtitle,
            initialBingeGroup = initialBingeGroup,
            pauseDescription = pauseDescription,
            onBack = onBack,
            onOpenInExternalPlayer = onOpenInExternalPlayer,
            onOpenExternalUrl = onOpenExternalUrl,
            modifier = modifier,
            logo = logo,
            poster = poster,
            background = background,
            seasonNumber = seasonNumber,
            episodeNumber = episodeNumber,
            episodeTitle = episodeTitle,
            episodeThumbnail = episodeThumbnail,
            contentType = contentType,
            videoId = videoId,
            parentMetaId = parentMetaId,
            parentMetaType = parentMetaType,
            providerAddonId = providerAddonId,
            torrentInfoHash = torrentInfoHash,
            torrentFileIdx = torrentFileIdx,
            torrentFilename = torrentFilename,
            torrentTrackers = torrentTrackers,
            initialPositionMs = initialPositionMs,
            initialProgressFraction = initialProgressFraction,
            contentLanguage = contentLanguage,
        )
    )
}
