package com.nuvio.app.features.player

import kotlinx.serialization.json.JsonObject

internal expect object PlayerSettingsStorage {
    fun loadShowLoadingOverlay(): Boolean?
    fun saveShowLoadingOverlay(enabled: Boolean)
    fun loadShowParentalGuide(): Boolean?
    fun saveShowParentalGuide(enabled: Boolean)
    fun loadResizeMode(): String?
    fun saveResizeMode(mode: String)
    fun loadHoldToSpeedEnabled(): Boolean?
    fun saveHoldToSpeedEnabled(enabled: Boolean)
    fun loadHoldToSpeedValue(): Float?
    fun saveHoldToSpeedValue(speed: Float)
    fun loadTouchGesturesEnabled(): Boolean?
    fun saveTouchGesturesEnabled(enabled: Boolean)
    fun loadExternalPlayerEnabled(): Boolean?
    fun saveExternalPlayerEnabled(enabled: Boolean)
    fun loadExternalPlayerForwardSubtitles(): Boolean?
    fun saveExternalPlayerForwardSubtitles(enabled: Boolean)
    fun loadExternalPlayerSendSkipSegments(): Boolean?
    fun saveExternalPlayerSendSkipSegments(enabled: Boolean)
    fun loadExternalPlayerId(): String?
    fun saveExternalPlayerId(playerId: String?)
    fun loadPreferredAudioLanguage(): String?
    fun savePreferredAudioLanguage(language: String)
    fun loadSecondaryPreferredAudioLanguage(): String?
    fun saveSecondaryPreferredAudioLanguage(language: String?)
    fun loadPreferredSubtitleLanguage(): String?
    fun savePreferredSubtitleLanguage(language: String)
    fun loadSecondaryPreferredSubtitleLanguage(): String?
    fun saveSecondaryPreferredSubtitleLanguage(language: String?)
    fun loadSubtitleTextColor(): String?
    fun saveSubtitleTextColor(colorHex: String)
    fun loadSubtitleBackgroundColor(): String?
    fun saveSubtitleBackgroundColor(colorHex: String)
    fun loadSubtitleOutlineColor(): String?
    fun saveSubtitleOutlineColor(colorHex: String)
    fun loadSubtitleOutlineEnabled(): Boolean?
    fun saveSubtitleOutlineEnabled(enabled: Boolean)
    fun loadSubtitleOutlineWidth(): Int?
    fun saveSubtitleOutlineWidth(width: Int)
    fun loadSubtitleBold(): Boolean?
    fun saveSubtitleBold(enabled: Boolean)
    fun loadSubtitleFontSizeSp(): Int?
    fun saveSubtitleFontSizeSp(fontSizeSp: Int)
    fun loadSubtitleBottomOffset(): Int?
    fun saveSubtitleBottomOffset(bottomOffset: Int)
    fun loadSubtitleStripSdh(): Boolean?
    fun saveSubtitleStripSdh(enabled: Boolean)
    fun loadSubtitleUseForcedSubtitles(): Boolean?
    fun saveSubtitleUseForcedSubtitles(enabled: Boolean)
    fun loadSubtitleShowOnlyPreferredLanguages(): Boolean?
    fun saveSubtitleShowOnlyPreferredLanguages(enabled: Boolean)
    fun loadStreamReuseLastLinkEnabled(): Boolean?
    fun saveStreamReuseLastLinkEnabled(enabled: Boolean)
    fun loadStreamReuseLastLinkCacheHours(): Int?
    fun saveStreamReuseLastLinkCacheHours(hours: Int)
    fun loadAndroidPlaybackEngine(): String?
    fun saveAndroidPlaybackEngine(engine: String)
    fun loadAndroidLibmpvVideoOutput(): String?
    fun saveAndroidLibmpvVideoOutput(output: String)
    fun loadAndroidLibmpvHardwareDecodingEnabled(): Boolean?
    fun saveAndroidLibmpvHardwareDecodingEnabled(enabled: Boolean)
    fun loadAndroidLibmpvYuv420pEnabled(): Boolean?
    fun saveAndroidLibmpvYuv420pEnabled(enabled: Boolean)
    fun loadDecoderPriority(): Int?
    fun saveDecoderPriority(priority: Int)
    fun loadMapDV7ToHevc(): Boolean?
    fun saveMapDV7ToHevc(enabled: Boolean)
    fun loadTunnelingEnabled(): Boolean?
    fun saveTunnelingEnabled(enabled: Boolean)
    fun loadStreamAutoPlayMode(): String?
    fun saveStreamAutoPlayMode(mode: String)
    fun loadStreamAutoPlaySource(): String?
    fun saveStreamAutoPlaySource(source: String)
    fun loadStreamAutoPlaySelectedAddons(): Set<String>?
    fun saveStreamAutoPlaySelectedAddons(addons: Set<String>)
    fun loadStreamAutoPlaySelectedPlugins(): Set<String>?
    fun saveStreamAutoPlaySelectedPlugins(plugins: Set<String>)
    fun loadStreamAutoPlayRegex(): String?
    fun saveStreamAutoPlayRegex(regex: String)
    fun loadStreamAutoPlayTimeoutSeconds(): Int?
    fun saveStreamAutoPlayTimeoutSeconds(seconds: Int)
    fun loadSkipIntroEnabled(): Boolean?
    fun saveSkipIntroEnabled(enabled: Boolean)
    fun loadAnimeSkipEnabled(): Boolean?
    fun saveAnimeSkipEnabled(enabled: Boolean)
    fun loadAnimeSkipClientId(): String?
    fun saveAnimeSkipClientId(clientId: String)

    fun loadIntroDbApiKey(): String?
    fun saveIntroDbApiKey(apiKey: String)
    fun loadIntroSubmitEnabled(): Boolean?
    fun saveIntroSubmitEnabled(enabled: Boolean)
    fun loadStreamAutoPlayNextEpisodeEnabled(): Boolean?
    fun saveStreamAutoPlayNextEpisodeEnabled(enabled: Boolean)
    fun loadStreamAutoPlayNextEpisodeFallbackEnabled(): Boolean?
    fun saveStreamAutoPlayNextEpisodeFallbackEnabled(enabled: Boolean)
    fun loadStreamAutoPlayPreferBingeGroup(): Boolean?
    fun saveStreamAutoPlayPreferBingeGroup(enabled: Boolean)
    fun loadStreamAutoPlayReuseBingeGroup(): Boolean?
    fun saveStreamAutoPlayReuseBingeGroup(enabled: Boolean)
    fun loadNextEpisodeThresholdMode(): String?
    fun saveNextEpisodeThresholdMode(mode: String)
    fun loadNextEpisodeThresholdPercent(): Float?
    fun saveNextEpisodeThresholdPercent(percent: Float)
    fun loadNextEpisodeThresholdMinutesBeforeEnd(): Float?
    fun saveNextEpisodeThresholdMinutesBeforeEnd(minutes: Float)
    fun loadUseLibass(): Boolean?
    fun saveUseLibass(enabled: Boolean)
    fun loadLibassRenderType(): String?
    fun saveLibassRenderType(renderType: String)
    fun loadIosVideoOutputPreset(): String?
    fun saveIosVideoOutputPreset(preset: String)
    fun loadIosToneMappingMode(): String?
    fun saveIosToneMappingMode(mode: String)
    fun loadIosTargetPrimaries(): String?
    fun saveIosTargetPrimaries(primaries: String)
    fun loadIosTargetTransfer(): String?
    fun saveIosTargetTransfer(transfer: String)
    fun loadIosHardwareDecoderMode(): String?
    fun saveIosHardwareDecoderMode(mode: String)
    fun loadIosAudioOutputMode(): String?
    fun saveIosAudioOutputMode(mode: String)
    fun loadIosExtendedDynamicRangeEnabled(): Boolean?
    fun saveIosExtendedDynamicRangeEnabled(enabled: Boolean)
    fun loadIosTargetColorspaceHintEnabled(): Boolean?
    fun saveIosTargetColorspaceHintEnabled(enabled: Boolean)
    fun loadIosHdrComputePeakEnabled(): Boolean?
    fun saveIosHdrComputePeakEnabled(enabled: Boolean)
    fun loadIosDebandEnabled(): Boolean?
    fun saveIosDebandEnabled(enabled: Boolean)
    fun loadIosInterpolationEnabled(): Boolean?
    fun saveIosInterpolationEnabled(enabled: Boolean)
    fun loadIosBrightness(): Int?
    fun saveIosBrightness(value: Int)
    fun loadIosContrast(): Int?
    fun saveIosContrast(value: Int)
    fun loadIosSaturation(): Int?
    fun saveIosSaturation(value: Int)
    fun loadIosGamma(): Int?
    fun saveIosGamma(value: Int)
    fun exportToSyncPayload(): JsonObject
    fun replaceFromSyncPayload(payload: JsonObject)
}
