import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../design/tokens.dart';
import '../models/movie.dart';
import '../services/continue_watching_service.dart';
import '../services/download_service.dart';
import '../services/font_service.dart';
import '../services/user_library_service.dart';
import '../services/watch_analytics_service.dart';
import '../services/watch_metadata_service.dart';
import '../widgets/app_card.dart';
import '../widgets/cinematic_3d_backdrop.dart';

const _gold = AppDesignTokens.goldMuted;
const _bg = AppDesignTokens.backgroundCanvas;

class WatchAnalyticsScreen extends StatefulWidget {
  const WatchAnalyticsScreen({super.key});
  @override State<WatchAnalyticsScreen> createState() => _WatchAnalyticsScreenState();
}

class _WatchAnalyticsScreenState extends State<WatchAnalyticsScreen> {
  final _analytics = WatchAnalyticsService.instance;
  final _library = UserLibraryService.instance;
  final _metadata = WatchMetadataService();
  List<Map<String,dynamic>> _continue = [];
  WatchMetadataSummary? _meta;
  bool _loadingMeta = true;

  @override void initState() { super.initState(); _analytics.addListener(_refresh); _library.addListener(_refresh); _load(); }
  @override void dispose() { _analytics.removeListener(_refresh); _library.removeListener(_refresh); super.dispose(); }
  void _refresh() { if (mounted) setState(() {}); }
  Future<void> _load() async {
    try { _continue = await ContinueWatchingService.getEntries(); } catch (_) {}
    try { _meta = await _metadata.summarize(_library.watched); } catch (_) {}
    if (mounted) setState(() => _loadingMeta = false);
  }

  List<Movie> get _watched => _library.watched;
  List<Movie> get _watchlist => _library.watchlist;
  List<Map<String,dynamic>> get _watchEvents => _analytics.events.where((e)=>e['type']=='watched').toList();
  int _year(Movie m) => int.tryParse(m.releaseYear) ?? 0;

  Map<String,int> _decades() { final out=<String,int>{}; for(final m in _watched){final y=_year(m); if(y>=1900){final d='${(y~/10)*10}s'; out[d]=(out[d]??0)+1;}} return out; }
  Map<String,int> _types() { var movies=0,shows=0; for(final m in _watched){if(m.mediaType.toLowerCase()=='tv')shows++;else movies++;} return {'Movies':movies,'TV Shows':shows}; }
  List<int> _weekdayCounts(){final c=List<int>.filled(7,0);for(final e in _watchEvents){final t=DateTime.fromMillisecondsSinceEpoch((e['timestamp'] as num?)?.toInt()??0);if(t.year>1970)c[t.weekday-1]++;}return c;}
  List<int> _monthCounts(){final c=List<int>.filled(12,0),n=DateTime.now();for(final e in _watchEvents){final t=DateTime.fromMillisecondsSinceEpoch((e['timestamp'] as num?)?.toInt()??0);final d=(n.year-t.year)*12+n.month-t.month;if(d>=0&&d<12)c[11-d]++;}return c;}
  List<int> _watchlistGrowth(){final c=List<int>.filled(12,0),n=DateTime.now();for(final e in _analytics.events.where((e)=>e['type']=='watchlist_add')){final t=DateTime.fromMillisecondsSinceEpoch((e['timestamp'] as num?)?.toInt()??0);final d=(n.year-t.year)*12+n.month-t.month;if(d>=0&&d<12)c[11-d]++;}return c;}
  List<String> _monthLabels(){final n=DateTime.now();const names=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return List.generate(12,(i)=>names[DateTime(n.year,n.month-(11-i),1).month-1]);}
  Map<String,int> _ratings(){final m={for(var i=1;i<=5;i++)'$i':0};for(final r in _analytics.ratings.values){final k=r.round().clamp(1,5).toString();m[k]=(m[k]??0)+1;}return m;}
  double get _avgRating=>_analytics.ratings.isEmpty?0:_analytics.ratings.values.reduce((a,b)=>a+b)/_analytics.ratings.length;

  @override Widget build(BuildContext context){
    final types=_types(), decades=_decades(), ratings=_ratings(), total=math.max(1,_watched.length);
    return Cinematic3DBackdrop(intensity:.7,child:Scaffold(backgroundColor:_bg,appBar:AppBar(backgroundColor:Colors.transparent,elevation:0,titleSpacing:18,title:Text('Your viewing analytics',style:FontService.instance.style(color:Colors.white,fontSize:21,fontWeight:FontWeight.w800)),leading:IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back_rounded,color:Colors.white))),body:ListView(padding:const EdgeInsets.fromLTRB(16,4,16,36),children:[
      _hero(),
      _section(Icons.campaign_outlined,'Directors you watch most','Ranked by titles you have watched',_Rankings(data:_meta?.directors,empty:'Watch titles to build your director ranking.')),
      _section(Icons.movie_creation_outlined,'What you watch','By content type',_TypeBars(types:types,total:total)),
      _section(Icons.local_movies_outlined,'Across the decades','Titles by release era',_DecadeChart(data:decades)),
      _section(Icons.calendar_month_outlined,'Your week','Watched titles by weekday',_VerticalBars(values:_weekdayCounts(),labels:const ['M','T','W','T','F','S','S'])),
      _section(Icons.bookmark_border_rounded,'Watchlist growth','Titles saved · last 12 months',_VerticalBars(values:_watchlistGrowth(),labels:_monthLabels())),
      _section(Icons.emoji_events_outlined,'Milestones','How far you have made it through your personal canon',_Milestones(watched:_watched.length)),
      _section(Icons.star_outline_rounded,'Your ratings','How you score what you watch',Column(children:[_RatingsChart(average:_avgRating,ratings:ratings),const SizedBox(height:12),_RateTitles(titles:_watched)])),
      _section(Icons.calendar_today_outlined,'Your watching rhythm','Titles watched · last 12 months',_VerticalBars(values:_monthCounts(),labels:_monthLabels())),
      _section(Icons.auto_awesome_outlined,'Genres · Countries · Languages','Most watched across your library',_loadingMeta?const SizedBox(height:48,child:Center(child:CircularProgressIndicator(strokeWidth:2,color:_gold))):_MetadataBreakdown(meta:_meta)),
      _section(Icons.groups_2_outlined,'Cast you watch most','Repeated cast members',_Rankings(data:_meta?.cast,empty:'Watch titles to build your cast ranking.')),
      _section(Icons.play_circle_outline_rounded,'Currently watching','Resume points saved on this device',_ContinueWatching(entries:_continue)),
      _section(Icons.download_outlined,'Downloads','Offline library snapshot',_DownloadSummary()),
      AppCard(borderRadius:BorderRadius.circular(22),padding:const EdgeInsets.all(14),child:const Row(children:[Icon(Icons.insights_rounded,color:_gold,size:20),SizedBox(width:10),Expanded(child:Text('Analytics are calculated from your local FEB library. Playback completion and library changes are recorded automatically; ratings are stored locally on this device.',style:TextStyle(color:Colors.white54,fontSize:11,height:1.4)))])),
    ])));
  }

  Widget _hero()=>AppCard(borderRadius:BorderRadius.circular(24),padding:const EdgeInsets.all(18),backgroundColor:Colors.white.withValues(alpha:.045),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:42,height:42,decoration:BoxDecoration(color:_gold.withValues(alpha:.14),borderRadius:BorderRadius.circular(14)),child:const Icon(Icons.insights_rounded,color:_gold)),const SizedBox(width:12),Expanded(child:Text('Your watching profile',style:FontService.instance.style(color:Colors.white,fontSize:18,fontWeight:FontWeight.w800)))]),const SizedBox(height:16),Row(children:[_mini('${_watched.length}','Watched'),_mini('${_watchlist.length}','Watchlist'),_mini('${_continue.length}','In progress'),_mini('${DownloadService.instance.items.length}','Downloads')]) ]));
  Widget _mini(String v,String l)=>Expanded(child:Column(children:[Text(v,style:const TextStyle(color:_gold,fontSize:21,fontWeight:FontWeight.w800)),const SizedBox(height:3),Text(l,style:const TextStyle(color:Colors.white38,fontSize:9))]));
  Widget _section(IconData icon,String title,String subtitle,Widget child)=>Padding(padding:const EdgeInsets.only(top:12),child:AppCard(borderRadius:BorderRadius.circular(24),padding:const EdgeInsets.fromLTRB(16,16,16,15),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:38,height:38,decoration:BoxDecoration(color:_gold.withValues(alpha:.11),borderRadius:BorderRadius.circular(12)),child:Icon(icon,color:_gold,size:19)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w800)),const SizedBox(height:2),Text(subtitle,style:const TextStyle(color:Colors.white38,fontSize:10))]))]),const SizedBox(height:15),child])));
}

class _TypeBars extends StatelessWidget{final Map<String,int> types;final int total;const _TypeBars({required this.types,required this.total});@override Widget build(BuildContext c)=>Column(children:types.entries.map((e){final p=e.value/total;return Padding(padding:const EdgeInsets.only(bottom:12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(e.key,style:const TextStyle(color:Colors.white70,fontSize:13)),Text('${(p*100).round()}% · ${e.value}',style:const TextStyle(color:Colors.white54,fontSize:12))]),const SizedBox(height:7),ClipRRect(borderRadius:BorderRadius.circular(8),child:LinearProgressIndicator(value:p,minHeight:8,backgroundColor:Colors.white10,valueColor:const AlwaysStoppedAnimation(_gold))) ]));}).toList());}}
class _DecadeChart extends StatelessWidget{final Map<String,int> data;const _DecadeChart({required this.data});@override Widget build(BuildContext c){if(data.isEmpty)return const _EmptyState(text:'Watch more titles to build your decade profile.');final es=data.entries.toList()..sort((a,b)=>a.key.compareTo(b.key));final max=es.map((e)=>e.value).fold<int>(1,(a,b)=>a>b?a:b);return SizedBox(height:170,child:Column(children:[Expanded(child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:es.map((e)=>Expanded(child:Padding(padding:const EdgeInsets.symmetric(horizontal:4),child:Column(mainAxisAlignment:MainAxisAlignment.end,children:[Text('${e.value}',style:const TextStyle(color:Colors.white54,fontSize:10)),const SizedBox(height:4),Container(height:105*e.value/max,decoration:BoxDecoration(color:_gold.withValues(alpha:.75),borderRadius:const BorderRadius.vertical(top:Radius.circular(8))))])))).toList())),const SizedBox(height:7),Row(children:es.map((e)=>Expanded(child:Text(e.key,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white38,fontSize:9)))).toList())]));}}
class _VerticalBars extends StatelessWidget{final List<int> values;final List<String> labels;const _VerticalBars({required this.values,required this.labels});@override Widget build(BuildContext c){final max=values.fold<int>(1,(a,b)=>a>b?a:b);return SizedBox(height:170,child:Column(children:[Expanded(child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:List.generate(values.length,(i)=>Expanded(child:Padding(padding:const EdgeInsets.symmetric(horizontal:3),child:Column(mainAxisAlignment:MainAxisAlignment.end,children:[Text('${values[i]}',style:const TextStyle(color:Colors.white38,fontSize:9)),const SizedBox(height:4),Container(height:105*values[i]/max,decoration:BoxDecoration(color:values[i]==max&&values[i]>0?_gold:Colors.white.withValues(alpha:.035),borderRadius:const BorderRadius.vertical(top:Radius.circular(7))))]))))),),const SizedBox(height:7),Row(children:List.generate(labels.length,(i)=>Expanded(child:Text(labels[i],textAlign:TextAlign.center,style:const TextStyle(color:Colors.white38,fontSize:8))))]));}}
class _Milestones extends StatelessWidget{final int watched;const _Milestones({required this.watched});@override Widget build(BuildContext c){const goals=[25,50,100,150,250,500];return Wrap(spacing:10,runSpacing:14,children:goals.map((g){final p=(watched/g).clamp(0.0,1.0);return SizedBox(width:(MediaQuery.sizeOf(c).width-74)/2,child:Column(children:[SizedBox(width:82,height:82,child:Stack(alignment:Alignment.center,children:[CircularProgressIndicator(value:p,strokeWidth:6,backgroundColor:Colors.white10,valueColor:const AlwaysStoppedAnimation(_gold)),Text('${(p*100).round()}%',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w800))])),const SizedBox(height:6),Text('$g titles',style:const TextStyle(color:Colors.white,fontSize:12,fontWeight:FontWeight.w700)),Text('$watched of $g',style:const TextStyle(color:Colors.white38,fontSize:9))]));}).toList());}}
class _RatingsChart extends StatelessWidget{final double average;final Map<String,int> ratings;const _RatingsChart({required this.average,required this.ratings});@override Widget build(BuildContext c)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Text(average==0?'—':average.toStringAsFixed(1),style:const TextStyle(color:_gold,fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(width:8),Text('avg · ${ratings.values.fold<int>(0,(a,b)=>a+b)} ratings',style:const TextStyle(color:Colors.white54,fontSize:11))]),const SizedBox(height:12),SizedBox(height:105,child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:ratings.entries.map((e){final max=ratings.values.fold<int>(1,(a,b)=>a>b?a:b);return Expanded(child:Padding(padding:const EdgeInsets.symmetric(horizontal:4),child:Column(mainAxisAlignment:MainAxisAlignment.end,children:[Text('${e.value}',style:const TextStyle(color:Colors.white38,fontSize:8)),Container(height:78*e.value/max,decoration:BoxDecoration(color:_gold.withValues(alpha:.85),borderRadius:const BorderRadius.vertical(top:Radius.circular(6)))),const SizedBox(height:4),Text(e.key,style:const TextStyle(color:Colors.white38,fontSize:8))])));}).toList()))]);}}
class _RateTitles extends StatelessWidget{final List<Movie> titles;const _RateTitles({required this.titles});@override Widget build(BuildContext c){if(titles.isEmpty)return const _EmptyState(text:'Mark a title watched to rate it here.');return Column(children:titles.take(8).map((m)=>Padding(padding:const EdgeInsets.only(bottom:8),child:Row(children:[Expanded(child:Text(m.title,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white70,fontSize:11))),...List.generate(5,(i){final active=WatchAnalyticsService.instance.ratingFor(m)>=i+1;return IconButton(padding:EdgeInsets.zero,constraints=const BoxConstraints.tightFor(width:26,height:30),onPressed:()=>WatchAnalyticsService.instance.setRating(m,i+1.0),icon:Icon(active?Icons.star_rounded:Icons.star_border_rounded,size:17,color:active?_gold:Colors.white24));})]))).toList());}}
class _Rankings extends StatelessWidget{final Map<String,int>? data;final String empty;const _Rankings({required this.data,required this.empty});@override Widget build(BuildContext c){final es=(data??{}).entries.toList()..sort((a,b)=>b.value.compareTo(a.value));if(es.isEmpty)return _EmptyState(text:empty);return Column(children:es.take(5).map((e)=>Padding(padding:const EdgeInsets.only(bottom:8),child:Row(children:[Expanded(child:Text(e.key,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white70,fontSize:11))),Text('${e.value}',style:const TextStyle(color:_gold,fontSize:11,fontWeight:FontWeight.w800))]))).toList());}}
class _MetadataBreakdown extends StatelessWidget{final WatchMetadataSummary? meta;const _MetadataBreakdown({required this.meta});@override Widget build(BuildContext c){if(meta==null)return const _EmptyState(text:'Metadata could not be loaded. Your local library remains available.');return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[_list('GENRES',meta!.genres),const SizedBox(height:12),_list('COUNTRIES',meta!.countries),const SizedBox(height:12),_list('LANGUAGES',meta!.languages)]);}Widget _list(String label,Map<String,int> data){final es=data.entries.toList()..sort((a,b)=>b.value.compareTo(a.value));return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,style:const TextStyle(color:Colors.white38,fontSize:9,letterSpacing:1.2)),const SizedBox(height:7),...es.take(4).map((e)=>Padding(padding:const EdgeInsets.only(bottom:7),child:Column(children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(e.key,style:const TextStyle(color:Colors.white70,fontSize:11)),Text('${e.value}',style:const TextStyle(color:Colors.white54,fontSize:10))]),const SizedBox(height:4),ClipRRect(borderRadius:BorderRadius.circular(5),child:LinearProgressIndicator(value:e.value/es.first.value,minHeight:6,backgroundColor:Colors.white10,valueColor:const AlwaysStoppedAnimation(_gold)))])))]);}}
class _ContinueWatching extends StatelessWidget{final List<Map<String,dynamic>> entries;const _ContinueWatching({required this.entries});@override Widget build(BuildContext c){if(entries.isEmpty)return const _EmptyState(text:'Nothing in progress right now.');return Column(children:entries.take(5).map((e){final m=ContinueWatchingService.movieFromEntry(e);if(m==null)return const SizedBox.shrink();final p=(e['duration'] as num?)?.toInt()??0;final pos=(e['position'] as num?)?.toInt()??0;final r=p>0?(pos/p).clamp(0.0,1.0):0.0;return Padding(padding:const EdgeInsets.only(bottom:10),child:Row(children:[ClipRRect(borderRadius:BorderRadius.circular(8),child:Image.network(m.posterUrl,width:42,height:60,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(width:42,height:60,color:Colors.white10))),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(m.title,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white,fontSize:12,fontWeight:FontWeight.w700)),const SizedBox(height:7),LinearProgressIndicator(value:r,minHeight:5,backgroundColor:Colors.white10,valueColor:const AlwaysStoppedAnimation(_gold)),const SizedBox(height:4),Text('${(r*100).round()}% watched',style:const TextStyle(color:Colors.white38,fontSize:9))]))]));}).toList());}}
class _DownloadSummary extends StatelessWidget{@override Widget build(BuildContext c){final n=DownloadService.instance.items.length;return Row(children:[_s('$n','Saved'),_s('$n','Local'),_s('$n','Tracked')]);}Widget _s(String v,String l)=>Expanded(child:Column(children:[Text(v,style:const TextStyle(color:_gold,fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:3),Text(l,style:const TextStyle(color:Colors.white38,fontSize:9))]));}}
class _EmptyState extends StatelessWidget{final String text;const _EmptyState({required this.text});@override Widget build(BuildContext c)=>Container(width:double.infinity,padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white.withValues(alpha:.025),borderRadius:BorderRadius.circular(14)),child:Text(text,style:const TextStyle(color:Colors.white38,fontSize:10.5,height:1.4)));}
