name: FEB
description: A media streaming and downloading application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.8.2
  screen_brightness: ^2.0.0
  flutter_volume_controller: ^1.2.0
  http: ^1.2.0
  html: ^0.15.4
  dio: ^5.4.0
  cached_network_image: ^3.3.1
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.5
  flutter_inappwebview: ^6.1.5
  wakelock_plus: ^1.1.4
  cupertino_icons: ^1.0.8
  youtube_player_flutter: ^9.1.0
  flutter_local_notifications: ^22.3.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  # Added for local storage persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.6
  speech_to_text: ^7.3.0
  ota_update: ^7.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_eval: ^0.7.0
  
  # --- NEW ADDED PACKAGES ---
  google_sign_in: ^6.1.5
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  sign_in_with_apple: ^6.1.0
  package_info_plus: ^8.1.0
  open_filex: ^4.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Added for generating Hive adapters
  hive_generator: ^2.0.1
  build_runner: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: AstoneNouvea
      fonts:
        - asset: assets/fonts/Astone Nouvea.ttf
          weight: 400

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/fab.jpg
    - shorebird.yaml

# --- CORRECTLY PLACED AT THE ROOT LEVEL ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21