// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-_AupnLbVlWt7yYrLwIxJC0ajWpt3QDg',
    appId: '1:341624343876:web:28e6b1f2a59dbd09b75b11',
    messagingSenderId: '341624343876',
    projectId: 'mela-backend',
    authDomain: 'mela-backend.firebaseapp.com',
    storageBucket: 'mela-backend.firebasestorage.app',
    measurementId: 'G-1RM4LH33PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7lsEMUXceYkNEafRWquKQmujij_8_HVM',
    appId: '1:341624343876:android:c9087e24ae721d5db75b11',
    messagingSenderId: '341624343876',
    projectId: 'mela-backend',
    storageBucket: 'mela-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8h4w0bOy7OJyq7mmnWjecO2diHMkoUN8',
    appId: '1:341624343876:ios:8bbecdbee0b3b5dcb75b11',
    messagingSenderId: '341624343876',
    projectId: 'mela-backend',
    storageBucket: 'mela-backend.firebasestorage.app',
    androidClientId: '341624343876-cl0fid9ec69ifn5ogjl5efh1i4g229j0.apps.googleusercontent.com',
    iosClientId: '341624343876-4l4f1lfmrt4oitmmt75gt16uu2nk3liq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mela',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8h4w0bOy7OJyq7mmnWjecO2diHMkoUN8',
    appId: '1:341624343876:ios:8bbecdbee0b3b5dcb75b11',
    messagingSenderId: '341624343876',
    projectId: 'mela-backend',
    storageBucket: 'mela-backend.firebasestorage.app',
    androidClientId: '341624343876-cl0fid9ec69ifn5ogjl5efh1i4g229j0.apps.googleusercontent.com',
    iosClientId: '341624343876-4l4f1lfmrt4oitmmt75gt16uu2nk3liq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mela',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-_AupnLbVlWt7yYrLwIxJC0ajWpt3QDg',
    appId: '1:341624343876:web:728ee814347d8787b75b11',
    messagingSenderId: '341624343876',
    projectId: 'mela-backend',
    authDomain: 'mela-backend.firebaseapp.com',
    storageBucket: 'mela-backend.firebasestorage.app',
    measurementId: 'G-RD81KKCLVZ',
  );
}
